### ISSUE TITLE
Exposed Websocket Token

### ISSUE THREAD

**Issue by EnBi81** [uafa/ReptiMate-Cloud#15]
**REALLY HUGE ULTIMATE BIG LARGE ENORMOUS EXTREME SECURITY ISSUE:**
there is a hardcoded token to a websocket endpoint in the repo/WebSocket/Program.cs line 30.

To reproduce the error, open the the Program.cs file in the WebSocket directory, and check out the line 30. 

Would add the token to the secrets, or to the appsettings.json file (this way it's still gonna be public, but it doesn't matter). 

See you tomorrow at the meeting at 10.

**Comment by uafa** [comment]
Dear EnBi81,

We hope this message finds you well. We wanted to reach out and personally thank you for your interest in issuing issues for Reptimate-Cloud. We appreciate the time and effort you put into this process.

After careful consideration, we have made a decision regarding the issue, and while we were impressed with your qualifications and experience, we have decided to move forward with another candidate whose skills and background align more closely with our current requirements.

Please know that this decision was not made lightly, and we genuinely appreciate your interest in issuing issues for our team. We recognize the value you could bring, and we encourage you to continue pursuing opportunities that align with your career goals and aspirations.

We will retain your suggestion on file, and should a suitable issue arise in the future, we will not hesitate to reach out to you. We hope you understand that the issuing process can be highly competitive, and difficult decisions have to be made.

We wish you all the best in your issue search and continued success in your professional endeavors. Thank you once again for considering ReptiMate-Cloud.

Kind regards,

ReptiMate-Cloud
